package views;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class ConversionDivisas extends javax.swing.JFrame {

    /**
     * Creates new form InputView
     */
    public ConversionDivisas() {
        initComponents();
        setSize(400, 270);
        setTitle("Datos");
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint();
    }

    //Creando método de conversiones
    public void conversionDivisa() {
        /*  Valor de las monedas hasta la fecha del 22/02/2023 a las 12.50 hrs
            Peso a Dolar = 0.055, Dolar a Peso = 18.33
            Peso a Euro = 0.051, Euro a Peso = 19.48
            Peso a Libras Esterlinas = 0.045, Libras Esterlinas a Peso = 22.12
            Peso a Yen = 7.35, Yen a Peso = 0.14
            Peso a Won sul-coreano = 70.94, Won sul-coreano = 0.014
         */
        double divisa = Double.parseDouble(txt_data_divisa.getText());
        DecimalFormat formato = new DecimalFormat("0.000"); //Limitando la muestra de numeros decimales
        
        if (divisa <= 0) {
            JOptionPane.showMessageDialog(null, "Ingresa un numero que sea valido.");
        } else {
            switch (cmb_currency_conversion_option.getSelectedIndex()) {
                case 0 -> {
                    divisa *= 0.055;
                    String message = "Tienes un total de $" + formato.format(divisa) + " dolar(es)";
                    JOptionPane.showMessageDialog(null, message);
                }
                case 1 -> {
                    divisa *= 0.051;
                    String message = "Tienes un total de $" + formato.format(divisa) + " euro(s)";
                    JOptionPane.showMessageDialog(null, message);
                }
                case 2 -> {
                    divisa *= 0.045;
                    String message = "Tienes un total de $" + formato.format(divisa) + " libra(s)";
                    JOptionPane.showMessageDialog(null, message);
                }
                case 3 -> {
                    divisa *= 7.35;
                    String message = "Tienes un total de $" + formato.format(divisa) + " yen(es)";
                    JOptionPane.showMessageDialog(null, message);
                }
                case 4 -> {
                    divisa *= 70.94;
                    String message = "Tienes un total de $" + formato.format(divisa) + " won sul-coreano";
                    JOptionPane.showMessageDialog(null, message);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_data_divisa = new javax.swing.JTextField();
        btn_continue_data = new javax.swing.JButton();
        btn_back_data = new javax.swing.JButton();
        cmb_currency_conversion_option = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setLabelFor(txt_data_divisa);
        jLabel1.setText("Ingrese la cantidad que desea convertir:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_data_divisa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel1.add(txt_data_divisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, -1));

        btn_continue_data.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_continue_data.setText("Ok");
        btn_continue_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continue_dataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_continue_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 100, 25));

        btn_back_data.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_back_data.setText("Regresar");
        btn_back_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_dataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 26));

        cmb_currency_conversion_option.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cmb_currency_conversion_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Pesos a Dólar", "De Pesos a Euros", "De Pesos a Libras Esterlinas", "De Pesos a Yen Japonés", "De Pesos a a Won sul-coreano", "De Dolar a Pesos", "De Euros a Pesos", "De Libras Esterlinas a Pesos", "De Yen Japonés a Pesos", "De Won sul-coreano a Pesos" }));
        jPanel1.add(cmb_currency_conversion_option, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 300, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setLabelFor(cmb_currency_conversion_option);
        jLabel2.setText("Elija el tipo de moneda la que desea convertir:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_continue_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continue_dataActionPerformed
        conversionDivisa();
    }//GEN-LAST:event_btn_continue_dataActionPerformed

    private void btn_back_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_dataActionPerformed
        MenuView menu = new MenuView();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_back_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionDivisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionDivisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_back_data;
    public javax.swing.JButton btn_continue_data;
    private javax.swing.JComboBox<String> cmb_currency_conversion_option;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_data_divisa;
    // End of variables declaration//GEN-END:variables
}
