package views;

import Controllers.TemperaturaController;

/**
 *
 * @author angel
 */
public class ConversionTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConversionMedidas
     */
    public ConversionTemperatura() {
        initComponents();
        setSize(460, 300);
        setTitle("Datos");
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint();

        //Controlador de la vista
        TemperaturaController controller_temp = new TemperaturaController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_input_temp = new javax.swing.JTextField();
        cmb_option_temp = new javax.swing.JComboBox<>();
        btn_enter_temp = new javax.swing.JButton();
        btn_back_temp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setLabelFor(txt_input_temp);
        jLabel1.setText("Ingresa la temperatura que desea convertir:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setLabelFor(cmb_option_temp);
        jLabel2.setText("Selecciona al tipo que desea convertir:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, -1, -1));

        txt_input_temp.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jPanel1.add(txt_input_temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 70, 350, -1));

        cmb_option_temp.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        cmb_option_temp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius a Fahrenheit", "Celsius a Kelvin", "Fahrenheit a Celsius", "Fahrenheit a Kelvin", "Kelvin a Celsius", "Kelvin a Fahrenheit" }));
        cmb_option_temp.setRequestFocusEnabled(false);
        jPanel1.add(cmb_option_temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 155, 300, -1));

        btn_enter_temp.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btn_enter_temp.setText("Ok");
        jPanel1.add(btn_enter_temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 110, -1));

        btn_back_temp.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        btn_back_temp.setText("Regresar");
        btn_back_temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_tempActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back_temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 210, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back_tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_tempActionPerformed
        MenuView menu = new MenuView();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_back_tempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back_temp;
    public javax.swing.JButton btn_enter_temp;
    public javax.swing.JComboBox<String> cmb_option_temp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_input_temp;
    // End of variables declaration//GEN-END:variables
}
