package views;

import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class InputView extends javax.swing.JFrame {

    /**
     * Creates new form InputView
     */
    public InputView() {
        initComponents();
        setSize(400, 180);
        setTitle("Datos");
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint();
    }

    //double conversor = Double.parseDouble(txt_data.getText());



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        btn_continue_data = new javax.swing.JButton();
        btn_back_data = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese la cantidad que desea convertir:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_data.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataActionPerformed(evt);
            }
        });
        jPanel1.add(txt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, -1));

        btn_continue_data.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_continue_data.setText("Siguiente");
        btn_continue_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continue_dataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_continue_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 105, -1, 25));

        btn_back_data.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_back_data.setText("Regresar");
        jPanel1.add(btn_back_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 105, -1, 26));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataActionPerformed

    }//GEN-LAST:event_txt_dataActionPerformed

    private void btn_continue_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continue_dataActionPerformed
        if (txt_data.getText().equals("") || Double.parseDouble(txt_data.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "Ingresa un numero valido");
            txt_data.setText("");
        } else {
            ConversionOptionsView option_view = new ConversionOptionsView();
            option_view.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_continue_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_back_data;
    public javax.swing.JButton btn_continue_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_data;
    // End of variables declaration//GEN-END:variables
}
